#define CM_PER_L3_CLKSTCTRL                     0x44E00004
#define CM_PER_L3_CLKSTCTRL_CLKTRCTRL_SW_WKUP   0x2u
#define CM_PER_L3_CLKSTCTRL_CLKTRCTRL           0x3u

#define CM_PER_L3S_CLKSTCTRL                    0x44E0000C
#define CM_PER_L3S_CLKSTCTRL_CLKTRCTRL_SW_WKUP  0x2u
#define CM_PER_L3S_CLKSTCTRL_CLKTRCTRL          0x3u

